apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-addons-pv
  labels:
    app: web-addons-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/fachriza/mbiz/apps/odoo/odoo-kube/workspace"
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: web-addons-pvc
  name: web-addons-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
