apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-odoo-pv
  labels:
    app: web-odoo-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/fachriza/mbiz/apps/odoo/odoo-kube/src/odoo"
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: web-odoo-pvc
  name: web-odoo-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

