apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgadmin
  name: pgadmin
spec:
  ports:
  - name: http
    port: 5555
    protocol: TCP
    targetPort: http
  selector:
    app: pgadmin
  type: LoadBalancer
